In [2]:
import numpy as np 
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [3]:
iris = pd.read_csv('IRIS.csv')

In [4]:
iris.shape

(150, 5)

In [5]:
iris.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [6]:
iris.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [7]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [8]:
iris.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [9]:
iris['species'].value_counts()

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: species, dtype: int64

In [10]:

label_encoder = LabelEncoder()
iris['species'] = label_encoder.fit_transform(iris['species'])

In [11]:
iris.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [12]:
iris['species'].value_counts()

0    50
1    50
2    50
Name: species, dtype: int64

In [13]:
# Define features and target
X = iris.drop('species', axis=1)
y = iris['species']

# Split the data
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Display the shape of the training and testing sets
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(105, 4) (45, 4) (105,) (45,)


In [14]:
from sklearn import svm
clf = svm.SVC(kernel = 'poly', C = 1).fit(x_train, y_train)
train_accuracy = clf.score(x_train, y_train)
#validation_accuracy = clf.score(x_val, y_val)
svm_accuracy = clf.score(x_test, y_test)
print("accuracy:",train_accuracy)
#print('validation accuracy:',validation_accuracy)
print('SVM testing accuracy:',svm_accuracy)

accuracy: 0.9809523809523809
SVM testing accuracy: 0.9777777777777777


In [15]:
# Predict on the test set
from sklearn.metrics import mean_squared_error
y_pred = clf.predict(x_test)
accuracy = accuracy_score(y_test, y_pred)
# Compute and display the confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
mse_SVR =mean_squared_error(y_test,y_pred)
print(f"Mean Squared Error (MSE): {mse_SVR:.2f}")
print('Confusion Matrix:\n', conf_matrix)
print("Accuracy:", accuracy)
# Compute and display the classification report
class_report = classification_report(y_test, y_pred, target_names=label_encoder.classes_)
print('Classification Report:\n', class_report)

Mean Squared Error (MSE): 0.02
Confusion Matrix:
 [[19  0  0]
 [ 0 12  1]
 [ 0  0 13]]
Accuracy: 0.9777777777777777
Classification Report:
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        19
Iris-versicolor       1.00      0.92      0.96        13
 Iris-virginica       0.93      1.00      0.96        13

       accuracy                           0.98        45
      macro avg       0.98      0.97      0.97        45
   weighted avg       0.98      0.98      0.98        45

